# https://travis-ci.org/#!/phlax/systemd-docker

install:
  - docker-compose build systemd-docker

script:

  - docker-compose up -d systemd-docker
  - docker-compose logs systemd-docker

  # run commands in the container
  - docker-compose exec systemd-docker systemctl -l --no-pager status
  - docker-compose exec systemd-docker journalctl --all -l --no-pager

  # check dbus availability
  - docker-compose exec systemd-docker busctl --no-pager

  # stop the server
  - docker-compose stop systemd-docker
  - docker-compose logs systemd-docker

before_deploy:
  - echo $DOCKER_PASSWORD | docker login -u phlax --password-stdin

deploy:
  provider: script
  script: docker push phlax/systemd
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master)$
