# https://travis-ci.org/#!/phlax/systemd-docker
dist: trusty
sudo: true
language: python
services:
  - docker

before_install:
  - "echo '{\"storage-driver\": \"overlay2\"}' | sudo tee /etc/docker/daemon.json"
  - sudo service docker restart

install:
  - pip install -U docker-compose
  - docker-compose build systemd-docker

script:

  - docker-compose up -d systemd-docker

  - docker-compose logs systemd-docker

  # run commands in the containr
  - docker-compose exec systemd-docker systemctl -l --no-pager status
  - docker-compose exec systemd-docker journalctl --all -l --no-pager

  # check dbus availability
  - docker-compose exec systemd-docker busctl --no-pager

  # stop the server
  - docker-compose stop systemd-docker
  - docker-compose logs systemd-docker

after_success:

  - docker tag phlax/systemd-docker phlax/systemd
  - docker login -u phlax -p "$DOCKER_PASSWORD"
  - docker push phlax/systemd
