# docker-compose for phlax/systemd-docker
#
version: "2.4"
services:

  systemd-docker:
    image: phlax/systemd
    tty: true
    build:
      context: ./docker
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
    - /run
    - /run/lock
    - /tmp
